name: cen_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.23
  image_picker: ^1.1.2
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  logger: ^2.4.0
  envied: ^1.0.0
  location: ^7.0.1
  dart_geohash: ^2.1.0
  geocoding: ^3.0.0
  fluttertoast: ^8.2.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  supabase_flutter: ^2.8.0
  google_fonts: ^6.2.1
  share_plus: ^10.1.2
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  envied_generator: ^1.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/locations.json
